force-app/main/default/objects/Litmos_Team__c/Litmos_Team__c.object-meta.xml
<CustomObject>
    <label>Litmos Team</label>
    <nameField>
        <label>Litmos Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Litmos Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Litmos_Team__c/fields/Litmos_Id__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Id__c</fullName>
    <description>Id obtained from Litmos</description>
    <externalId>true</externalId>
    <label>Litmos Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Litmos_Team__c/fields/Litmos_Parent_Team__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Parent_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Holds parent team</description>
    <label>Litmos Parent Team</label>
    <referenceTo>Litmos_Team__c</referenceTo>
    <relationshipLabel>Litmos Sub-Teams</relationshipLabel>
    <relationshipName>Litmos_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Team__c/fields/Trigger_Number_of_Subteams__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Number_of_Subteams__c</fullName>
    <description>Holds the total number of subteams. Does not include subteams of children. Populated by trigger. Formula field will be used to display on record page.</description>
    <label>Trigger Number of Subteams</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/litmosTeamsNumSubteamsFlowTEST.cls
@isTest
public class litmosTeamsNumSubteamsFlowTEST {
    @isTest
    static void testNumSubteams() {
        List<Litmos_Team__c> teams = new List<Litmos_Team__c>();
        for(Integer i = 0; i < 5; i++) {
            teams.add(new Litmos_Team__c(
                Name='Test team ' + i,
                Litmos_Id__c = 'TESTTEAM' + i
            ));
        }

        insert teams;
        for(Integer i = 1; i < 5; i++) {
            teams[i].Litmos_Parent_Team__c = teams[0].Id;
        }
        //confirm no parent teams on team[0]
        Litmos_Team__c parent = [SELECT Id,Trigger_Number_of_Subteams__c FROM Litmos_Team__c WHERE Id=:teams[0].Id];
        System.assertEquals(0, parent.Trigger_Number_of_Subteams__c);
        Test.startTest();
        update teams;
        Test.stopTest();

        parent = [SELECT Id, Trigger_Number_of_Subteams__c FROM Litmos_Team__c WHERE Id=: teams[0].Id];
        System.assertEquals(4, parent.Trigger_Number_of_Subteams__c);
    }
}