force-app/main/default/objects/Litmos_Team__c/Litmos_Team__c.object-meta.xml
<CustomObject>
    <label>Litmos Team</label>
    <nameField>
        <label>Litmos Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Litmos Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Litmos_Team__c/fields/Litmos_Id__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Id__c</fullName>
    <description>Id obtained from Litmos</description>
    <externalId>true</externalId>
    <label>Litmos Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Litmos_Team_Member__c/Litmos_Team_Member__c.object-meta.xml
<CustomObject>
    <description>Associates users with team members</description>
    <label>Litmos Team Member</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>Litmos Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litmos Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Litmos_Team_Member__c/fields/Learner__c.field-meta.xml
<CustomField>
    <fullName>Learner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learner</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Litmos Team Members</relationshipLabel>
    <relationshipName>Litmos_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Team_Member__c/fields/Litmos_Team__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Team__c</fullName>
    <label>Litmos Team</label>
    <referenceTo>Litmos_Team__c</referenceTo>
    <relationshipLabel>Litmos Team Members</relationshipLabel>
    <relationshipName>Litmos_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Litmos_Team_Member__c/fields/Litmos_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Litmos_User_Id__c</fullName>
    <label>Litmos User Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Litmos_Team_Member__c/fields/Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Member_Type__c</fullName>
    <label>Member Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Learner</fullName>
                <default>true</default>
                <label>Learner</label>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/litmosTeamsControllerTEST.cls
@isTest
public class litmosTeamsControllerTEST {
    @isTest
    static void testGetAdmins() {
        Profile standardUser = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User admin = new User(
            FirstName = 'Admin',
            LastName = 'AdminUser',
            ProfileId = standardUser.Id,
            isActive = true,
            email='admin@adminuser.com',
            Username='admin@adminuser.com',
            alias='admin',
            TimeZoneSidKey='America/New_York',
            LocaleSidKey='en_US',
            EmailEncodingKey='UTF-8',
            LanguageLocaleKey='en_US'
        );
        Litmos_Team__c team = new Litmos_Team__c(
            Name='Test Team',
            Litmos_Id__c='ABCDE'
        );
        insert team;
        insert admin;
        Litmos_Team_Member__c member = new Litmos_Team_Member__c(
            Learner__c = admin.Id,
            Litmos_Team__c = team.Id,
            Member_Type__c = 'Admin',
            Litmos_User_Id__c = 'ADMINUSER1'
        );
        insert member;

        Test.startTest();
        List<Litmos_Team_Member__c> admins = litmosTeamsController.getAdmins(team.Id);
        Test.stopTest();
        System.assertEquals(1, admins.size());
    }
    @isTest
    static void testGetLeaders() {
        Profile standardUser = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User leader = new User(
            FirstName = 'Leader',
            LastName = 'LeadUser',
            ProfileId = standardUser.Id,
            isActive = true,
            email='lead@adminuser.com',
            Username='lead@adminuser.com',
            alias='leadr',
            TimeZoneSidKey='America/New_York',
            LocaleSidKey='en_US',
            EmailEncodingKey='UTF-8',
            LanguageLocaleKey='en_US'
        );
        Litmos_Team__c team = new Litmos_Team__c(
            Name='Test Team',
            Litmos_Id__c='ABCDE'
        );
        insert team;
        insert leader;
        Litmos_Team_Member__c member = new Litmos_Team_Member__c(
            Learner__c = leader.Id,
            Litmos_Team__c = team.Id,
            Member_Type__c = 'Admin',
            Litmos_User_Id__c = 'ADMINUSER1'
        );
        insert member;

        Test.startTest();
        List<Litmos_Team_Member__c> leaders = litmosTeamsController.getLeaders(team.Id);
        Test.stopTest();
        System.assertEquals(1, leaders.size());
    }
}