force-app/main/default/objects/Litmos_Team__c/Litmos_Team__c.object-meta.xml
<CustomObject>
    <label>Litmos Team</label>
    <nameField>
        <label>Litmos Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Litmos Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Litmos_Team__c/fields/Litmos_Id__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Id__c</fullName>
    <description>Id obtained from Litmos</description>
    <externalId>true</externalId>
    <label>Litmos Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Litmos_Team_Member__c/Litmos_Team_Member__c.object-meta.xml
<CustomObject>
    <description>Associates users with team members</description>
    <label>Litmos Team Member</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>Litmos Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litmos Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Litmos_Team_Member__c/fields/Learner__c.field-meta.xml
<CustomField>
    <fullName>Learner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learner</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Litmos Team Members</relationshipLabel>
    <relationshipName>Litmos_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Team_Member__c/fields/Litmos_Team__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Team__c</fullName>
    <label>Litmos Team</label>
    <referenceTo>Litmos_Team__c</referenceTo>
    <relationshipLabel>Litmos Team Members</relationshipLabel>
    <relationshipName>Litmos_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Litmos_Team_Member__c/fields/Litmos_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Litmos_User_Id__c</fullName>
    <label>Litmos User Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LitmosTeamsQueueProcessing.cls
public class LitmosTeamsQueueProcessing implements Queueable{
    private Map<Id, List<Object>> mapMembers;
    
    public LitmosTeamsQueueProcessing(Map<Id, List<Object>> members) {
        this.mapMembers = members;
    }
    public void execute(QueueableContext context) {
        //list of teams included
        List<Litmos_Team__c> teams = [SELECT Id,Litmos_Id__c FROM Litmos_Team__c WHERE Id IN : mapMembers.keySet()];
        List<Litmos_Team_Member__c> members = new List<Litmos_Team_Member__c>();
        Set<String> litmosIds = new Set<String>();
        for(Id memId : mapMembers.keySet()) {
            for(Object o : mapMembers.get(memId)) {
                Map<String, Object> newMap = (Map<String,Object>) o;
                members.add(new Litmos_Team_Member__c(
                	Litmos_Team__c = memId,
                    Litmos_User_Id__c = String.valueOf(newMap.get('Id'))
                ));
                litmosIds.add(String.valueOf(newMap.get('Id')));
            }
        }
        //users
        List<User> users = [SELECT Id, Litmos__LitmosUserId__c FROM User WHERE Litmos__LitmosUserId__c IN : litmosIds AND isActive = true AND Litmos__Litmos_Activated__c = true];
        List<Litmos_Team_Member__c> updates = new List<Litmos_Team_Member__c>();
        for(User u : users) {
            for(Litmos_Team_Member__c mem : members) {
                if(mem.Litmos_User_Id__c == u.Litmos__LitmosUserId__c) {
                    mem.Learner__c = u.Id;
                    updates.add(mem);
                }
            }
        }
        insert updates;
    }
}